import Head from 'next/head';
import {ReactNode} from 'react';

export function Site(props: { children: ReactNode }) {
    return <><Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link
            href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400&family=Playfair+Display:wght@400;700;800&display=swap"
            rel="stylesheet"/>
    </Head>
        <div className="flex flex-col px-4 lg:px-0 lg:flex-row mx-auto max-w-[800px] lg:mx-0 lg:max-w-none lg:h-screen">
            <div className="bg-dark p-6 text-white">
                <div className="font-serif text-2xl">gntmhub</div>
            </div>
            <div className="lg:max-w-[800px] lg:mx-auto  lg:max-h-screen lg:overflow-y-auto">
                {props.children}
            </div>
        </div>
    </>;
}