import { useUser } from '@auth0/nextjs-auth0';
import {PrismaClient} from '@prisma/client'
import type {NextPage} from 'next'
import Head from 'next/head'

const Home: NextPage<{posts:any}> = (props: {posts: any}) => {

    const { user, error, isLoading } = useUser();

    if (isLoading) return <div>Loading...</div>;
    if (error) return <div>{error.message}</div>;

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-red-400" >
        Test {JSON.stringify(props)}
          <a href="/api/auth/login">Login</a>
          <a href="/api/auth/logout">Logout</a>
      </main>

        {(
            user && (
                <div>
                    <img src={user.picture!} alt={user.name!} />
                    <p>{user.name}</p>
                    <p>{user.email}</p>
                </div>
            ))}

    </div>
  )
}

export async function getServerSideProps(){
  const prisma = new PrismaClient();
  return {props: {posts: (await prisma.post.findMany()).map(x => ({...x, createdAt: null}))}};
}

export default Home
